name = "DifferentialEvolution"
uuid = "b32b9a76-dd00-46da-ba81-3c2dea8ff9d4"
authors = ["Lewis Grozinger <l.grozinger2@ncl.ac.uk>"]
version = "0.1.0"

[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
